// <auto-generated />
using System;
using EchoBoard.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EchoBoard.Infrastructure.Migrations;

[DbContext(typeof(EchoBoardDbContext))]
[Migration("20260705190000_AddAppSettings")]
partial class AddAppSettings
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

        modelBuilder.Entity("EchoBoard.Domain.Entities.AppSetting", b =>
            {
                b.Property<string>("Key")
                    .HasMaxLength(160)
                    .HasColumnType("TEXT");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("Value")
                    .IsRequired()
                    .HasMaxLength(2048)
                    .HasColumnType("TEXT");

                b.HasKey("Key");

                b.ToTable("AppSettings", (string)null);
            });

        modelBuilder.Entity("EchoBoard.Domain.Entities.Category", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(80)
                    .HasColumnType("TEXT")
                    .UseCollation("NOCASE");

                b.Property<int>("SortOrder")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.HasIndex("Name")
                    .IsUnique();

                b.HasIndex("SortOrder");

                b.ToTable("Categories", (string)null);
            });

        modelBuilder.Entity("EchoBoard.Domain.Entities.HotkeyBinding", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT");

                b.Property<int?>("GlobalCommand")
                    .HasColumnType("INTEGER");

                b.Property<bool>("IsEnabled")
                    .HasColumnType("INTEGER");

                b.Property<int>("Modifiers")
                    .HasColumnType("INTEGER");

                b.Property<string>("NormalizedKeyCombination")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .UseCollation("NOCASE");

                b.Property<string>("PrimaryKey")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("TEXT");

                b.Property<Guid?>("SoundId")
                    .HasColumnType("TEXT");

                b.Property<int>("TargetKind")
                    .HasColumnType("INTEGER");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("GlobalCommand")
                    .IsUnique()
                    .HasFilter("GlobalCommand IS NOT NULL");

                b.HasIndex("NormalizedKeyCombination")
                    .IsUnique();

                b.HasIndex("SoundId")
                    .IsUnique()
                    .HasFilter("SoundId IS NOT NULL");

                b.ToTable("HotkeyBindings", (string)null);
            });

        modelBuilder.Entity("EchoBoard.Domain.Entities.Sound", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT");

                b.Property<Guid?>("CategoryId")
                    .HasColumnType("TEXT");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT");

                b.Property<long>("Duration")
                    .HasColumnType("INTEGER");

                b.Property<string>("Extension")
                    .IsRequired()
                    .HasMaxLength(10)
                    .HasColumnType("TEXT");

                b.Property<string>("FilePath")
                    .IsRequired()
                    .HasMaxLength(1024)
                    .HasColumnType("TEXT")
                    .UseCollation("NOCASE");

                b.Property<long>("FileSize")
                    .HasColumnType("INTEGER");

                b.Property<bool>("IsFavorite")
                    .HasColumnType("INTEGER");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(120)
                    .HasColumnType("TEXT");

                b.Property<int>("SortOrder")
                    .HasColumnType("INTEGER");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("TEXT");

                b.Property<double>("Volume")
                    .HasColumnType("REAL");

                b.HasKey("Id");

                b.HasIndex("CategoryId");

                b.HasIndex("FilePath")
                    .IsUnique();

                b.HasIndex("IsFavorite");

                b.HasIndex("CategoryId", "SortOrder");

                b.ToTable("Sounds", (string)null);
            });

        modelBuilder.Entity("EchoBoard.Domain.Entities.HotkeyBinding", b =>
            {
                b.HasOne("EchoBoard.Domain.Entities.Sound", null)
                    .WithMany()
                    .HasForeignKey("SoundId")
                    .OnDelete(DeleteBehavior.Cascade);
            });

        modelBuilder.Entity("EchoBoard.Domain.Entities.Sound", b =>
            {
                b.HasOne("EchoBoard.Domain.Entities.Category", null)
                    .WithMany()
                    .HasForeignKey("CategoryId")
                    .OnDelete(DeleteBehavior.SetNull);
            });
#pragma warning restore 612, 618
    }
}
